### ISSUE TITLE
ERROR Z2M and converter lixee.js

### ISSUE THREAD

**Issue by seblang** [vk496/zigbee-herdsman-converters#1]
Error using Z2M DEV with Zigbee Herdsman library used by Z2M is 0.13.186 &   lixee.js (https://github.com/vk496/zigbee-herdsman-converters/blob/zlinky-integration/devices/lixee.js).

ZLINKY_DEBUG: Error seMetering/currentSummDelivered: Error: ConfigureReporting 0x00158d0005be9f7e/1 seMetering([{"attribute":"currentSummDelivered","minimumReportInterval":0,"maximumReportInterval":3600,"reportableChange":10}], {"timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":true,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null,"writeUndiv":false}) failed (Timeout - 12779 - 1 - 3 - 1794 - 7 after 10000ms)
Error configuring report for seMetering/currentSummDelivered
ZLINKY_DEBUG: Error liXeePrivate/tomorrowColor: Error: ConfigureReporting 0x00158d0005be9f7e/1 liXeePrivate([{"attribute":"tomorrowColor","minimumReportInterval":0,"maximumReportInterval":3600,"reportableChange":1}], {"timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":true,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":4151,"transactionSequenceNumber":null,"writeUndiv":false}) failed (Status 'UNSUPPORTED_ATTRIBUTE')
Error configuring report for liXeePrivate/tomorrowColor
ZLINKY_DEBUG: Error liXeePrivate/startNoticeEJP: Error: ConfigureReporting 0x00158d0005be9f7e/1 liXeePrivate([{"attribute":"startNoticeEJP","minimumReportInterval":0,"maximumReportInterval":3600,"reportableChange":1}], {"timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":true,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":4151,"transactionSequenceNumber":null,"writeUndiv":false}) failed (Status 'UNSUPPORTED_ATTRIBUTE')
Error configuring report for liXeePrivate/startNoticeEJP
ZLINKY_DEBUG: Error liXeePrivate/warnDPS: Error: ConfigureReporting 0x00158d0005be9f7e/1 liXeePrivate([{"attribute":"warnDPS","minimumReportInterval":0,"maximumReportInterval":3600,"reportableChange":1}], {"timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":true,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":4151,"transactionSequenceNumber":null,"writeUndiv":false}) failed (Status 'UNSUPPORTED_ATTRIBUTE')
Error configuring report for liXeePrivate/warnDPS
``

Other point, I am in standart mode and I am a producer.........i was expected to see the quantity of courant send in the network (like EAIT or INSTI)! But I have limited data :
Base 6915574Wh
Isousc 9A
Hchc 3763902Wh
Hchp 3063500Wh
Ejphn 3763902Wh
Ejphpm 3063500Wh
Bbrhcjb 3763902Wh
Bbrhpjb 3063500Wh
Bbrhcjw 12782Wh
Bbrhpjw 10169Wh
Bbrhcjr 41150Wh
Bbrhpjr 24071Wh
Iinst 2A
Imax 65535A

Ho can I improve this?
thank you

**Comment by vk496** [comment]
Hello, thank you for your feedback. I have the`EAIT` (currentSummDelivered) issue too (standard, single phase). In historique was working fine. I'm trying to figure why `ConfigureReporting` is not working

**Comment by vk496** [comment]
Seems a problem of subscription. I will disable it for now in order to debug more pricesily 

EDIT: @seblang could you check that now you can see the values?

**Comment by seblang** [comment]
Hi,

same issue :

ZLINKY_DEBUG: Error seMetering/currentSummDelivered: Error: ConfigureReporting 0x00158d0005be9f7e/1 seMetering([{"attribute":"currentSummDelivered","minimumReportInterval":0,"maximumReportInterval":3600,"reportableChange":10}], {"timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":true,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null,"writeUndiv":false}) failed (Timeout - 12779 - 1 - 3 - 1794 - 7 after 10000ms) Error configuring report for seMetering/currentSummDelivered ZLINKY_DEBUG: Error liXeePrivate/tomorrowColor: Error: ConfigureReporting 0x00158d0005be9f7e/1 liXeePrivate([{"attribute":"tomorrowColor","minimumReportInterval":0,"maximumReportInterval":3600,"reportableChange":1}], {"timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":true,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":4151,"transactionSequenceNumber":null,"writeUndiv":false}) failed (Status 'UNSUPPORTED_ATTRIBUTE') Error configuring report for liXeePrivate/tomorrowColor ZLINKY_DEBUG: Error liXeePrivate/startNoticeEJP: Error: ConfigureReporting 0x00158d0005be9f7e/1 liXeePrivate([{"attribute":"startNoticeEJP","minimumReportInterval":0,"maximumReportInterval":3600,"reportableChange":1}], {"timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":true,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":4151,"transactionSequenceNumber":null,"writeUndiv":false}) failed (Status 'UNSUPPORTED_ATTRIBUTE') Error configuring report for liXeePrivate/startNoticeEJP ZLINKY_DEBUG: Error liXeePrivate/warnDPS: Error: ConfigureReporting 0x00158d0005be9f7e/1 liXeePrivate([{"attribute":"warnDPS","minimumReportInterval":0,"maximumReportInterval":3600,"reportableChange":1}], {"timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":true,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":4151,"transactionSequenceNumber":null,"writeUndiv":false}) failed (Status 'UNSUPPORTED_ATTRIBUTE') Error configuring report for liXeePrivate/warnDPS ZLINKY_DEBUG: READ error liXeePrivate/currentTarif: Error: Read 0x00158d0005be9f7e/1 liXeePrivate(["currentTarif"], {"timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":true,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":4151,"transactionSequenceNumber":null,"writeUndiv":false}) failed (Status 'UNSUPPORTED_ATTRIBUTE') ZLINKY_DEBUG: READ error liXeePrivate/scheduleHPHC: Error: Read 0x00158d0005be9f7e/1 liXeePrivate(["scheduleHPHC"], {"timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":true,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":4151,"transactionSequenceNumber":null,"writeUndiv":false}) failed (Status 'UNSUPPORTED_ATTRIBUTE')

Result :

Base  7048729Wh

Isousc  9A

Hchc  3832194Wh

Hchp 3128363Wh

Ejphn 3832194Wh

Ejphpm  3128363Wh

Bbrhcjb  3832194Wh

Bbrhpjb  3128363Wh

Bbrhcjw 12782Wh

Bbrhpjw 10169Wh

Bbrhcjr  41150Wh

Bbrhpjr  24071Wh

Iinst  9A

Imax  65535A

N/A  39 LQI

**Comment by vk496** [comment]
@seblang are you sure that you are using the last version that I pushed yesterday? https://github.com/vk496/zigbee-herdsman-converters/blob/zlinky-integration/devices/lixee.js

In your logs I see error of report configurations, what is not done (for now) in the last version.

Also, you have BASE attribute, which should not exist for you if you are a produces (did you setup correctly the specific configuration of the device? You should toggle standard, phase single I guess and producer as ON)

**Comment by seblang** [comment]
@vk496 

sorry i was using the bad file.
after a trial this morning, no error ! I have choice standart + single phase + producer
I have these infos


EAIT
Total active power injected                   33042Wh

ERQ1
Total reactive power (Q1)                30306VArh

ERQ2
Total reactive power (Q2)                 176VArh

ERQ3
Total reactive power (Q3)               18001VArh

ERQ4
Total reactive power (Q4)                -22065VArh

SINSTI
Instantaneous apparent power injected           NulVA

SMAXIN
Apparent power max. injected n                 NulVA

SMAXIN-1
Apparent power max. injected n-1           NulVA

CCAIN
Point n of the withdrawn active load curve        NulW

CCAIN-1
Point n-1 of the withdrawn active load curve           NulW



**missing for me**

BBRHCJB
BBRHCJB index				
BBRHPJB
BBRHPJB index				
BBRHCJW
BBRHCJW index			
BBRHPJW
BBRHPJW index				
BBRHCJR
BBRHCJR index				
BBRHPJR
BBRHPJR index				
PAPP
Apparent power				
HCHC
HCHC index				
HCHP
HCHP index				


thank you

**Comment by vk496** [comment]
If you are a producer, that means that your linky is in Standard mode (you could check it phisically on the Linky). The attributes that you miss are intended for people in historique mode, not standard. Am I wrong?

Btw, if you are using last dev version of Z2M, you should also have some extra attributes (NGTF, LTARF, ....). If that is your case, could you give your output for **STGE** ? (Note: I updated it one more time)

**Comment by seblang** [comment]
@vk496 

Yes I confirm I am producer :-)

I was just using historique words not standard words.
I have upadte my Z2Medge and use the last lixee.js file (updated in last 4 hours ).


**Result for option standard + single_phase + NO-producer :**


ADSC
Serial Number  {"0":48,"1":54,"2":50,"3":48,"4":54,"5":49,"6":49,"7":53,"8":51,"9":51,"10":54,"11":54}
NGTF
Supplier pricing schedule name N/A
LTARF
Current supplier price label N/A
NTARF
Current tariff index number N/A
VTIC
Customer tele-information protocol version 2
DATE
Current date and time N/A
EAST
Total active power delivered 7062426Wh
EASF01
Total provider active power delivered (index 01) 3839445Wh
EASF02
Total provider active power delivered (index 02) 3134809Wh
EASF03
Total provider active power delivered (index 03) 12782Wh
EASF04
Total provider active power delivered (index 04) 10169Wh
EASF05
Total provider active power delivered (index 05) 41150Wh
EASF06
Total provider active power delivered (index 06) 24071Wh
EASF07
Total provider active power delivered (index 07) 0Wh
EASF08
Total provider active power delivered (index 08) 0Wh
EASF09
Total provider active power delivered (index 09) 0Wh
EASF10
Total provider active power delivered (index 10) 0Wh
EASD01
Active energy withdrawn Distributor (index 01) N/AWh
EASD02
Active energy withdrawn Distributor (index 02) N/AWh
EASD03
Active energy withdrawn Distributor (index 03) N/AWh
EASD04
Active energy withdrawn Distributor (index 04) N/AWh
IRMS1
RMS current 2A
URMS1
RMS voltage 228V
PREF
Apparent power of reference 9kVA
STGE
Register of Statutes N/A
PCOUP
Apparent power threshold N/AkVA
CCASN
Current point of the active load curve drawn 222W
CCASN-1
Previous point of the active load curve drawn 338W
UMOY1
Average RMS voltage (phase 1) 225V
SINSTS
Immediate apparent power delivered 536VA
SMAXN
Apparent power delivered peak 5097VA
SMAXN-1
Apparent power max. draw-off n-1 N/AVA
MSG1
Message short N/A
MSG2
Message ultra-short N/A
PRM
PRM number {"0":48,"1":54,"2":53,"3":50,"4":57,"5":48,"6":56,"7":56,"8":49,"9":57,"10":51,"11":51,"12":49,"13":48}
DPM1
Start mobile point 1 N/A
FPM1
Stop mobile point 1 N/A
DPM2
Start mobile point 2 N/A
FPM2
Stop mobile point 2 N/A
DPM3
Start mobile point 3 N/A
FPM3
Stop mobile point 3 N/A
RELAIS N/A
NJOURF
Current day number supplier calendar N/A
NJOURF+1
Next day number supplier calendar N/A
PJOURF+1
Profile of the next supplier calendar day N/A
PPOINTE1
Profile of the next check-in day N/A


**Result for option standard + single_phase + producer :**

EAIT
Total active power injected 33042Wh
ERQ1
Total reactive power (Q1) 30306VArh
ERQ2
Total reactive power (Q2) 176VArh
ERQ3
Total reactive power (Q3) 18001VArh
ERQ4
Total reactive power (Q4) -21488VArh
SINSTI
Instantaneous apparent power injected NulVA
SMAXIN
Apparent power max. injected n NulVA
SMAXIN-1
Apparent power max. injected n-1 NulVA
CCAIN
Point n of the withdrawn active load curve NulW
CCAIN-1
Point n-1 of the withdrawn active load curve NulW


**According ZLINKY-TIC (https://github.com/fairecasoimeme/Zlinky_TIC) for standard + single_phase + producer I can have :**

Fonctions Standard / MONO / PRODUCER	CLUSTER		Attribut
Standard : EAIT (Production)		0x0702		0x0001
Standard : EASF01			0x0702		0x0100
Standard : EASF02			0x0702		0x0102
Standard : EASF03			0x0702		0x0104
Standard : EASF04			0x0702		0x0106
Standard : EASF05			0x0702		0x0108
Standard : EASF06			0x0702		0x010A
Standard : EASF07			0x0702		0x010C
Standard : EASF08			0x0702		0x010E
Standard : EASF09			0x0702		0x0110
Standard : EASF10			0x0702		0x0112
Standard : PRM				0x0702		0x0307
Standard : ADSC				0x0702		0x0308
Standard: VTIC				0x0B01		0x000A
Standard : PREF				0x0B01		0x000D
Standard: PCOUP				0x0B01		0x000E
Standard : IRMS1			0x0B04		0x0508
Standard : SMAXN			0x0B04		0x050D
Standard : SINSTS			0x0B04		0x050F
Standard : ERQ1 (Production)		0x0B04		0x0305
Standard : ERQ2 (Production)		0x0B04		0x050E
Standard : ERQ3 (Production)		0x0B04		0x090E
Standard : ERQ4 (Production)		0x0B04		0x0A0E
Standard : URMS1(Mono / Triphasé)	0x0B04		0x0505
Standard : UMOY1(Mono / Triphasé)	0x0B04		0x0511
Standard : CCASN			0x0B04		0x050B
Standard : CCASN-1			0x0B04		0x090B
Standard :  NGTF			0xFF66		0x0000
Standard : LTARF			0xFF66		0x0200
Standard : NTARF			0xFF66		0x0201
Standard : DATE				0xFF66		0x0202
Standard : EASD01			0xFF66		0x0203
Standard : EASD02			0xFF66		0x0204
Standard : EASD03			0xFF66		0x0205
Standard : EASD04			0xFF66		0x0206
Standard : SINSTI (Production)		0xFF66		0x0207
Standard : SMAXIN (Production)		0xFF66		0x0208
Standard : SMAXIN-1 (Production)	0xFF66		0x0209
Standard : CCAIN (Production)		0xFF66		0x0210
Standard : CCAIN-1 (Production)		0xFF66		0x0211
Standard : SMAXN-1 (Monophasé)		0xFF66		0x0212
Standard : MSG1				0xFF66		0x0215
Standard : MSG2				0xFF66		0x0216
Standard : STGE				0xFF66		0x0217
Standard : DPM1				0xFF66		0x0218
Standard : FPM1				0xFF66		0x0219
Standard : DPM2				0xFF66		0x0220
Standard : FPM2				0xFF66		0x0221
Standard : DPM3				0xFF66		0x0222
Standard : FPM3				0xFF66		0x0223
Standard : RELAIS			0xFF66		0x0224
Standard : NJOURF			0xFF66		0x0225
Standard : NJOURF+1			0xFF66		0x0226
Standard : PJOURF+1			0xFF66		0x0227
Standard : PPOINTE1			0xFF66		0x0228

**Comment by vk496** [comment]
Thank you. I understand the problem. I will fix it in order to expose most of the stuff for producers.

With the data you show, I see that nothing from lixee cluster is shown to you. Which version/commit of Z2M are you using? I had exactly the same issue when I was using a Z2M version that was not using the last version of zigbee-herdsman-converters (which is required for lixxe clusters)

**Comment by seblang** [comment]
Thank you for your help

I am not sure i understood your question well ! I am using zigbee2mqtt@1.22.2-dev (Just cancelled and new downloaded this afternoon).

**Comment by vk496** [comment]
Yes, that version should have it. Regarding your problem for producer, now it should be fixed. Feel free to reopen the ticket if is not the case

**Comment by seblang** [comment]
Thank you for the converter! it's working fine.
You have added the OTA too :-)
Can you explain us how to update the firmware by OTA?
I have the file ZLinky router v3.0.ota, but what should I do with it?
sorry it's new for me :-)

**Comment by seblang** [comment]
Hi @vk496

It's working fine until your update! I can see regular update on my curve.

I will try again your previous command line :

for (const e of getCurrentConfig(device, options).filter((e) => !e.reportable)) {

Have a nice day
