### ISSUE TITLE
Support status : Not supported due to model: 'ZLinky_TIC\00'

### ISSUE THREAD

**Issue by roumano** [vk496/zigbee-herdsman-converters#10]
I can't anymore use the ZLinky_TIC LiXee,
i got a `Support status : Not supported`

I have try several version (some of them was working previously)
So i don't understand what's happen 
A new firmware version was apply on it ? 
```
Firmware build date : 20210401
Firmware version : 4000
```

**Comment by seblang** [comment]
Hi have you deleted and reload the add-on?

Are you sure you have the line in Config to inform z2m that he have to use
a converter?

**Comment by seblang** [comment]
Hi have you deleted and reload the add-on?

Are you sure you have the line in Config to inform z2m that he have to use a converter?

**Comment by seblang** [comment]
Hi have you deleted and reload the add-on?

Are you sure you have the line in Config to inform z2m that he have to use a converter?

**Comment by roumano** [comment]
I have try with :  
* external_converters:
  - converters/lixee.js
 
With the last version of https://gist.github.com/02de46e193bf111062f15be07d3e9bd2#gistcomment-3990294 (it's was working before)

* data/converters/lixee.js ( version of 5 days old)
it's was working before
* data/converters/lixee.js ( version of 5 days old) the current git version ( 5ebb703 )
Until today, never tested.
after testing it, (and the ota version also), i can use any version and don't understand why and a debug log it's not helpful to understand what's happen

**Comment by seblang** [comment]
Share the debug log please

**Comment by roumano** [comment]
Please found a debug of a start zigbee2mqtt and see the unsuported ( the device is 0x00158d0005d28481 )
But i don't find any usefull information with it
[debug.txt](https://github.com/vk496/zigbee-herdsman-converters/files/7835902/debug.txt)

Maybe i should try to delete and add it again with the debug mode ?

**Comment by roumano** [comment]
I think i found the issue (via the `DEBUG=zigbee-herdsman* npm start ...` ) : 
```
warn  2022-01-09 23:27:43: Received message from unsupported device with Zigbee model 'ZLinky_TIC\00' and manufacturer name 'LiXee'
```

I don't known from where the `\00` come but it's the issue.
with this modification on my file (lixee.js), it's now working :  
```
const definition = {
    zigbeeModel: ['ZLinky_TIC\00'],
    model: 'ZLinky_TIC\00',
```

I'm not sure if the firmware was upgraded wih the OTA but it's can be the origin of the issue

**Comment by vk496** [comment]
Hello,

This issue is very weird. Make sure that you have the last firmware. You will be able to update to the last version via OTA when I will push the integration to `dev`

Feel free to reopen the issue if you need

**Comment by roumano** [comment]
Can you notify me when you will push the integration to `dev` ?
