### ISSUE TITLE
Failed to insert into network

### ISSUE THREAD

**Issue by capi92** [vk496/zigbee-herdsman-converters#17]
1.23.0-dev commit: [6394d0f](https://github.com/Koenkk/zigbee2mqtt/commit/6394d0f)

Lixee Zlinky  tuning firmware 4000-0004 (i.e. latest availble via OTA update)

When inserting Zlinky into Zigbee Network device is associated, the left network, several times and then it's over.

See attached log in debug mode.

Any clue of what I'm doing wrong ? Is it a SW issue ? HW issue ?

NB : Linky running in standard mode, mono phase, no production.

error 2022-02-12 17:49:00: Failed to configure '0x00158d0005be865e', attempt 3 (Error: ConfigureReporting 0x00158d0005be865e/1 liXeePrivate([{"attribute":"tomorrowColor","minimumReportInterval":0,"maximumReportInterval":900,"reportableChange":1}], {"sendWhen":"immediate","timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":true,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":4151,"transactionSequenceNumber":null,"writeUndiv":false}) failed (Status 'UNSUPPORTED_ATTRIBUTE')
    at Endpoint.checkStatus (/app/node_modules/zigbee-herdsman/src/controller/model/endpoint.ts:317:28)
    at Endpoint.configureReporting (/app/node_modules/zigbee-herdsman/src/controller/model/endpoint.ts:649:22))

[zigbee2mqtt log.txt](https://github.com/vk496/zigbee-herdsman-converters/files/8054204/zigbee2mqtt.log.txt)

**Comment by vk496** [comment]
Could be a device failure. But the error in the logs is not related with it (the error should be fixed in https://github.com/Koenkk/zigbee-herdsman-converters/pull/3875)

**Comment by capi92** [comment]
Solved with HW modification
