### ISSUE TITLE
No consumption data by ZLinky

### ISSUE THREAD

**Issue by ullrik** [vk496/zigbee-herdsman-converters#19]
Hello,

I've been following the progress for a while and already thank you for the great work :)
I'm on the latest version of Zigbee2mqtt with the latest version of lixee.js. And I also did the OTA updates.
I don't know which variable informs my consumption because unfortunately I don't have any value that changes. And I have no errors in the logs.
This is what I have in HA:
![image](https://user-images.githubusercontent.com/3349917/155219101-06eca61d-5f5e-46a9-9090-c635a60e4070.png)
I imagine that I should have the consumption information with the variable "Zlinky TIC BASE"?

At the Zigbee2mqtt setting level, I left everything in automatic except "kWh_precision" which I have on 3:
  '0x00158d0005d29a88':
    friendly_name: ZLinky_TIC
    energy_phase: auto
    linky_mode: auto
    kWh_precision: 3
    tarif: auto
    production: auto
Normally, I am on a "Base" contract, in single phase and I do not produce electricity. 
I also see this log : Feb 22 22:10:21 raspberrypi npm[11554]: zlinky config: historique, single_phase, false, BASE

Do you have any idea where the problem could come from?
I was thinking of trying to reset everything to test :/

**Comment by vk496** [comment]
Hello,

The automatic detection of the config works partially. I suggest you to manually set your current configuration (standard/legacy, phase and production) and restart Z2M after that. The name of the HA attributes will changed based on you Linky mode.

Tomorrow 1st March should be released the stable version 1.24.0, where all changes will be available.

BTW: The contract type will just filter what Zigbee attributes is exposed to you. What really matters is Linky mode (standard or historique/legacy), which changes the names and give you more data (if you have the Linky in Standard)

**Comment by ullrik** [comment]
Hello, I just upgraded to version 1.24.0 with manual settings, everything is ok now. Thanks for your help :)
On the other hand, I have a delta between the information reported by the TIC and by the Enedis website... I will monitor this.
