### ISSUE TITLE
How to install ?

### ISSUE THREAD

**Issue by silversmarty** [vk496/zigbee-herdsman-converters#2]
Hello there!

I'm sorry, but it seems I'm unable to install the lixee.js file.

With the ralmn lixee.js file I succeeded (copying the file, modifying config) but it seems it's not the same procedure here. Can you please give more explanation?

- is zigbee-herdsman-converters already installed with every z2m installation?
- How to add lixee.js to my z2m repository as I can't find the right folder to paste it?
- should I need to replace "const exposes = require('../lib/exposes');" by "const exposes = require('zigbee-herdsman-converters/lib/exposes');" ?
- any other userfull information

Thanks a lot!

**Comment by seblang** [comment]
Hi @silversmarty

Yes you have to add zigbee-herdsman-converters instead of the point

**Comment by silversmarty** [comment]
Ok, but here is the error I've got when I do so (with the latest lixee.js version):

![image](https://user-images.githubusercontent.com/17980711/148112525-32aaba8e-1845-416c-89df-bcbf6edce57e.png)

**Comment by seblang** [comment]
fisrt you do not have the last version of ZM : zigbee2mqtt@1.22.2 and you have to use the Z2M edge because all update are not implemented in the standard version yet.

be sure that you have the last version of lixee.js => updated 2 hours ago

https://github.com/vk496/zigbee-herdsman-converters/blob/zlinky-integration/devices/lixee.js

**Comment by silversmarty** [comment]
That's right, I'm still on the stable version (not edge) but it seems I'll have to re-pair all my zigbee devices if I switch to Edge, and I don't want this :-(
Moreover, I can see there's a latest version of z2m but the "update" icon doesn't show up in HA Add-On as it should be ... I'll wait for this and re-try asap if it's the only thing to do.

Thanks

**Comment by silversmarty** [comment]
Oh, my z2m repository was not listed in the add-on repositories ! After adding it again, the updates to 1.22.2-1 shows up and lixee works perfectly : no need to switch to Edge !! Yeehaa !

**Comment by vk496** [comment]
Yeah, didn't noticed it. Some days ago was released a new stable version with all changes merged. So starting from Z2M 1.22.2 you can just put `lixee.js` as external converter and replace the imports. And it should work

**Comment by capi92** [comment]
Running: Zigbee2MQTT v1.22.2-1
Added linxee.js with path correction on expose.

nothing exposed and I got this error message.
Don't know is this is linked to same issue

 (node:384) UnhandledPromiseRejectionWarning: Error: Read 0x00158d0005be865e/1 haMeterIdentification([], {"timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":true,"direction":0,"srcEndpoint":null,"reservedBits":0,"manufacturerCode":null,"transactionSequenceNumber":null,"writeUndiv":false}) failed (Data request failed with error: 'No network route' (205))
    at ZStackAdapter.sendZclFrameToEndpointInternal (/app/node_modules/zigbee-herdsman/src/adapter/z-stack/adapter/zStackAdapter.ts:414:23)
    at Queue.executeNext (/app/node_modules/zigbee-herdsman/src/utils/queue.ts:32:32)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:384) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:384) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by capi92** [comment]
Hi,

I'm missing something during installation step.

Help appreciated...
Thanks,
Pierre 

config file:
const exposes = require('zigbee-herdsman-converters/lib/exposes');
const globalStore = require('zigbee-herdsman-converters/lib/store');
const {repInterval} = require('zigbee-herdsman-converters/lib/constants');
const reporting = require('zigbee-herdsman-converters/lib/reporting');
const {Buffer} = require('buffer');
const fz = require('zigbee-herdsman-converters/converters/fromZigbee');
const ea = exposes.access;
const ota = require('zigbee-herdsman-converters/lib/ota');

log:
[11:32:52] INFO: Handing over control to Zigbee2mqtt Core ...
> zigbee2mqtt@1.22.2 start
> node index.js
Zigbee2MQTT:error 2022-01-06 11:33:08: Failed to configure 'Linky', attempt 1 (Error: Bind 0x00158d0005be865e/1 seMetering from '0x00124b0024c27794/1' failed (AREQ - ZDO - bindRsp after 10000ms)
    at Timeout._onTimeout (/app/node_modules/zigbee-herdsman/src/utils/waitress.ts:64:35)
    at listOnTimeout (internal/timers.js:557:17)
    at processTimers (internal/timers.js:500:7))
