### ISSUE TITLE
No Value history in HA with the last converter

### ISSUE THREAD

**Issue by seblang** [vk496/zigbee-herdsman-converters#3]
@vk496 
Since yesterday evening ( start with the las converter) i have some issue :

Sensor  sinsts update ok and measurement history in HA ok

Sensors easf01 to easf06 + east value appear to be ok but no measurement history in HA

I have this issue in log from Z2M :

[services.d] done.
[08:51:37] INFO: Handing over control to Zigbee2mqtt Core ...
> zigbee2mqtt@1.22.2-dev start
> node index.js
Zigbee2MQTT:error 2022-01-05 08:56:22: Exception while calling fromZigbee converter: Buffer is not defined}
Zigbee2MQTT:error 2022-01-05 08:56:24: Exception while calling fromZigbee converter: Buffer is not defined}

**Comment by vk496** [comment]
Sorry, my fault. Fixed Buffer bug in 67728006.

Pls reopen if the HA history issue continue
