### ISSUE TITLE
Define which attributes should be in each configuration

### ISSUE THREAD

**Issue by vk496** [vk496/zigbee-herdsman-converters#5]
I'm not completely where each attribute should be. For example, I thought that **STGE** was only for Standard Linky mode (https://github.com/fairecasoimeme/Zlinky_TIC#synth%C3%A8se-d%C3%A9veloppeur) but since it encodes stuff like if the Linky is Standard or Historique mode, it should be in both.

I think I need a complete list of each possible configurations and what attributes should be there. Documents like **Enedis-NOI-CPT_54E.pdf** are the official documentation, but maybe there are some more stuff from Enedis

**Comment by ggrandou** [comment]
From what I know, the **Enedis-NOI-CPT_54E.pdf** describe the exact messages sent by Linky, both in _Historique_ and in _Standard_ mode. There is no such specific undocumented extension from Enedis.

STGE does not exist in _Historique_ mode which is by default the indication that we are not in _Standard_ mode.

Another option to de-cipher the mode is to look for the Meter Address:
- ADCO in _Historique_ mode
- ADSC in _Standard_ mode

I can send you raw _Historique_ mode traces if you're interested in (from TIC port, not from Zlinky).

**Comment by vk496** [comment]
Thank you for the info @ggrandou , it seems that STGE is only available in standard mode. But is weird that it contains info for linky mode.

Regarding to the serial, the problem is that both ADC0 and ADSC labels come from the same attribute (meterSerialNumber).

The traces would help me too :)

**Comment by ggrandou** [comment]
traces sent to your mailbox ;)

Regarding STGE, can't you use the fact that Zlinky returns NULL for STGE attribute to infer that it's in _Historique_ mode ?
Otherwise we can ask for a firmware update which would return a fake STGE value.

**Comment by vk496** [comment]
Thanks!

After discussing it in https://github.com/fairecasoimeme/Zlinky_TIC/issues/32, the v4 will give us directly the configuration needed
