### ISSUE TITLE
Problem during installation

### ISSUE THREAD

**Issue by Phenix21** [vk496/zigbee-herdsman-converters#7]
Hello

I would like tu use your converter with z2m and zlinky_TIC with a three phase electric meter and standard mode. The integration was OK with ralmn converter. 

After adding your lixee.js into zigbee/data/converters, I have this error and z2m don't start :

```
Using '/app/data' as data directory
(node:9) UnhandledPromiseRejectionWarning: internal/modules/cjs/loader.js:905

  throw err;
  ^
Error: Cannot find module '../lib/exposes'
Require stack:
- /app/dist/util/utils.js
- /app/dist/util/settings.js
- /app/index.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:902:15)
    at Function.Module._load (internal/modules/cjs/loader.js:746:27)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:93:18)
    at /app/dist/util/externally-loaded.js:2:17
    at Script.runInContext (vm.js:144:12)
    at Script.runInNewContext (vm.js:149:17)
    at Object.runInNewContext (vm.js:303:38)
    at loadModuleFromText (/app/lib/util/utils.ts:148:8)
    at loadModuleFromFile (/app/lib/util/utils.ts:155:12)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:9) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:9) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

About other informations : 

- Z2M is a docker container
- Z2M seems OK, it's the last version
![Capture d’écran 2022-01-05 205019](https://user-images.githubusercontent.com/62190259/148279898-07518b24-99f8-4826-8036-75bf9ca27a44.jpg)

Can you help me ? 
Thanks (and sorry for my english ;) )

**Comment by silversmarty** [comment]
Hello @Phenix21,
answer has been given here : https://github.com/vk496/zigbee-herdsman-converters/issues/2#issuecomment-1005101174

Cheers ;-)

**Comment by Phenix21** [comment]
Hi

I try it, thanks !

Edit : after installing zigbee-herdsman-converters, it's OK for the converter. 
@silversmarty thanks for the help !
@vk496 and @ralmn thanks for the work !

**Comment by vk496** [comment]
@Phenix21 could you please validate that lixee clusters works properly for you? (Any of NGTF, LTARIF, OPTARIF, STGE....)

Also, could you please share your current Linky config (mode, phase and if producer) and the STGE value that is reported to you?

Thanks in advice

**Comment by Phenix21** [comment]
I will check it tomorrow.

Actually i have a three-phase electric meter in standard mode, without production. 
The STGE value report is "Nul"
![image](https://user-images.githubusercontent.com/62190259/148295206-eeb1d9de-0c95-4b16-9b82-613673e456ed.png)

**Comment by vk496** [comment]
@Koenkk sorry for bother you, but do you know why the custom cluster is not working for people using the latest version of Z2M with the zigbee-herdsman up to date too? They import the lixee.js as external converter and manually fix the imports.

In my side I manually build the project and link the directories of the dependencies in my PC. But since the masterbof Z2M is already using the correct version, they should work too.... But this is not the first person reporting the same issue

**Comment by Phenix21** [comment]
Hello @vk496 

I'm not sure what king of informations you need, and what are lixee clusters, but i'm trying to help you.

You can see bellow my z2m configuration : 
![image](https://user-images.githubusercontent.com/62190259/148381677-e316b290-2452-47b5-a691-0df234e9600e.png)

Using this parameters, I have this informations on z2m interface : 
![image](https://user-images.githubusercontent.com/62190259/148381783-5a5fa166-9623-4171-9e61-2f36e58c9372.png)
![image](https://user-images.githubusercontent.com/62190259/148381822-2d17e480-2b04-419e-8734-14f61a7494e4.png)

In the clusters page : 
![image](https://user-images.githubusercontent.com/62190259/148381931-7ff7fcb4-54c2-4bbc-b625-ccbc1ea65820.png)

In HA I don't have the same informations : 
![image](https://user-images.githubusercontent.com/62190259/148382523-5774009d-5a34-42c5-890c-f0526ffa9dcf.png)

Tell me if you need more informations
