### ISSUE TITLE
Buffer is not defined

### ISSUE THREAD

**Issue by silversmarty** [vk496/zigbee-herdsman-converters#8]
Hello,

An error pops up regularly in my logs about buffer : "Exception while calling fromZigee converter : Buffer is not defined)".

![image](https://user-images.githubusercontent.com/17980711/148280709-da422243-1b6e-4cff-bacf-0e7c1f87c1cd.png)

Is there something to change in the lixee.js file ? Especially about the buffer line which is commented ?

Thanks

**Comment by seblang** [comment]
Hi

I think you are not using the last version of file (updated today for this issue)

https://github.com/vk496/zigbee-herdsman-converters/blob/zlinky-integration/devices/lixee.js

**Comment by silversmarty** [comment]
I've just uploaded the latest version, but the issue is still there :-(

**Comment by seblang** [comment]
are you sure that you have this at the begininf of the file :

const {Buffer} = require('buffer');

or 

//const {Buffer} = require('buffer');

**Comment by silversmarty** [comment]
I think so :

![image](https://user-images.githubusercontent.com/17980711/148294562-81e8ca6a-fdc2-46cd-a9d1-60807ac261b1.png)

**Comment by seblang** [comment]
Redémarre ha complètement

**Comment by silversmarty** [comment]
ça a l'air ok en effet ! Merci ;-)
